#!/bin/bash

printf "\n\ndo you have sqlite installed? y/n\n"
read USERIN

sqlfiletar="sqlite-autoconf-3380200.tar.gz"
sqlurl="https://www.sqlite.org/2022/"
sqlfile="sqlite-autoconf-3380200"
DBFILENAME="crowdshop_dev_db.db"

if [[ "$USERIN" = "n" ]];
then
  	printf "\nyou answered no, now downloading and installing sqlite\n\n"
	brew install sqlite
fi

echo "\nmaking db file if it doesn't exist\n"
if [[ ! -f $DBFILENAME ]]; then
	touch crowdshop_dev_db.db
fi

crowdpath=$(echo $(readlink -f $DBFILENAME))
mainpath=${crowdpath//\//\//}

cd crowdshop_api
echo "\ncreating env file in $(pwd)\n"

if [[ ! -d "env" ]]; then
	python3 -m venv env
fi

source env/bin/activate


export SQLALCHEMY_DATABASE_URI=sqlite://$mainpath
export SQLALCHEMY_TRACK_MODIFICATIONS=False
export FLASK_ENV=development
export PYTHONPATH=crowdshop_api

pip install -r requirements.txt

python3 run.py

